### ISSUE TITLE
Edit and continue?

### ISSUE THREAD

**Issue by iProgramMC** [SethRobinson/proton#18]
I've tried a lot of stuff to make edit and continue work (VS 2022), yet I couldn't get it to work. When I tried to make it work, I got the following error:
```
Edit and Continue : error  : The dependency information for 'App.cpp' in the state (*.idb) file(s) '' is out of sync with the Program Database (*.pdb) file 'Z:\proton\RTBareBones\bin\RTBareBones.pdb' for 'RTBareBones.exe'. Ensure that the file is compiled with the Enable Minimal Rebuild (/Gm) option.
```

Yet, it is compiled with /Gm:
![image](https://user-images.githubusercontent.com/17717494/190864210-f58380c5-2705-4589-b0fa-debf6a1ac62e.png)

**Comment by SethRobinson** [comment]
I've always had problems with edit and continue, kind of gave up on using it like 10 years ago.  let me know if you ever get it to work

**Comment by iProgramMC** [comment]
It seems like I got edit and continue working on an RTSimpleApp-based project, all I needed to do was turn /SAFESEH to "No". I'm not sure that's actually as safe but it works, and release builds can keep having it on
