### ISSUE TITLE
compile 

### ISSUE THREAD

**Issue by ardayildiz0** [SethRobinson/proton#21]
i cant downloand visual studio 2017 i have vs 2022 how can i compile thre are any other ways?

**Comment by SethRobinson** [comment]
Oh, Visual Studio 2022 should be fine.  I know RTConsole still has "windows_vc2017" as the project directory name, but I think it's actually a 2022 project inside, the dir just needs to be renamed.  

If it is actually a 2017 project, 2022 should auto-update it ok.
