### ISSUE TITLE
Problems with fullscreen

### ISSUE THREAD

**Issue by mar4ello6** [SethRobinson/proton#31]
Why was [this line](https://github.com/SethRobinson/proton/blob/6b1474e75a2acf48d848c70fcb043ce8223001a9/shared/BaseApp.cpp#L746) commented out? Without it fullscreen isn't actually fullscreen.
![image](https://github.com/SethRobinson/proton/assets/44264356/45d1d927-f70b-4d81-9d66-a96dbf6e82d7)

**Comment by SethRobinson** [comment]
Oops, you're exactly right, that line shouldn't be commented out.  Fixed, thanks!
