### ISSUE TITLE
Windows build causes command window to pop up for half a second

### ISSUE THREAD

**Issue by iProgramMC** [SethRobinson/proton#4]
Hi, I'm having an issue (if it is one), the command prompt is popping up for half a second when I start the app. Is that normal?

**Comment by Bexpg-0** [comment]
ye normal

**Comment by iProgramMC** [comment]
Do you have any experience with PSDK? You sound like you don't. Growtopia never shows up a command window before showing the game window, for example.

**Comment by Bexpg-0** [comment]
protonsdk is an old project, there are better game engines than this one. Instead of trying to copy Growtopia, I suggest you make a new game with your own ideas. I understand that this can be difficult for a 15-year-old, seth maybe a 10-15-year-old game programmer what about you? I think you started programming 1-2 years ago because of a video you saw, I looked at your projects and I can say that all your projects are programs trash so my advice is to stop trying to copy Growtopia.

**Comment by iProgramMC** [comment]
Are we really trying to create a conflict out of nothing? Screw you, I have better things to do.

> I can say that all your projects are programs trash
Yeah, right. And your projects are the best.

I'm pretty sure nobody asked for your opinion. I asked for help with PSDK. You are off topic. Please leave this conversation.

**Comment by iProgramMC** [comment]
> I think you started programming 1-2 years ago because of a video you saw

Your thought is wrong in this case, I actually started about 4 years ago.

> so my advice is to stop trying to copy Growtopia.

I'm not even trying.

> I suggest you make a new game with your own ideas. I understand that this can be difficult for a 15-year-old, 

It hardly is, and I am.

**Comment by Bexpg-0** [comment]
So, did you start coding at the age of 10? You don't have a single game in 4 years.

**Comment by Bexpg-0** [comment]
> > seth maybe a 10-15-year-old game programmer what about you?
> 
> LMAO he's actually roughly 40.

I mean, seth has been coding for 10 and 15 years. So you? 4 years and you don't even have a single game

**Comment by iProgramMC** [comment]
> > > seth maybe a 10-15-year-old game programmer what about you?
> > 
> > 
> > LMAO he's actually roughly 40.
> 
> I mean, seth has been coding for 10 and 15 years. So you? 4 years and you don't even have a single game

I do. I actually develop things other than games as well, I don't spend time developing games as much as I would've liked. Still, it's a cool job to have.

**Comment by DrOreo002** [comment]
Whats wrong with you? @Bexpg-0 , hes just asking a normal question

**Comment by iProgramMC** [comment]
Don't give him attention, he's just probably selling beygtah roms for da $mackar00nies

**Comment by Bexpg-0** [comment]
> Don't give him attention, he's just probably selling beygtah roms for da $mackar00nies

????

**Comment by iProgramMC** [comment]
oh sorry I confused you with the beta kid (from SM64 communities)

well you're still probably a kid that can't do a thing other than complain

**Comment by iProgramMC** [comment]
Let's not continue this discussion, please. I don't feel like doing it anymore.

**Comment by Bexpg-0** [comment]
> Let's not continue this discussion, please. I don't feel like doing it anymore.
I wasn't arguing with you if you wanna argue with me you gotta grow up first and stop your childish behavior

**Comment by Bexpg-0** [comment]
> Whats wrong with you? @Bexpg-0 , hes just asking a normal question

He f1cking ret4rded i already answered his questions "protonsdk trash and useless" I told her to use another program

**Comment by iProgramMC** [comment]
> > Let's not continue this discussion, please. I don't feel like doing it anymore.
> 
> I wasn't arguing with you if you wanna argue with me you gotta grow up first and stop your childish behavior

Meanwhile you said that it was normal, when it clearly wasn't as other Proton SDK apps don't do this. Then, I asked you if you had the knowledge to comment on that (more than I did), to which you started a useless argument. 



> > Whats wrong with you? @Bexpg-0 , hes just asking a normal question
> 
> He f1cking ret4rded i already answered his questions "protonsdk trash and useless" I told her to use another program

What if I want to use Proton SDK? What if I have a program that's written using that already that I plan to release soon, but there isn't much time to move to another engine? Please ask yourself these questions before suggesting I move to a different game engine/library.

**Comment by Bexpg-0** [comment]
>What if I have a program that's written using that already that I plan to release soon
.
No you dont have

**Comment by iProgramMC** [comment]
Please stop assuming that I don't have a Proton SDK project ongoing just because I do not have one publicly posted on my GitHub page. And please stop. If you consider this an argument, prepare to be hit by the truth: you aren't going to win it at all.

**Comment by iProgramMC** [comment]
Closing thread.

**Comment by Bexpg-0** [comment]
we both know that an idiot like you can't make game with protonsdk

**Comment by Bexpg-0** [comment]
I wanted to help you, but now it looks like you don't need help anymore. because you closed issues

**Comment by iProgramMC** [comment]
> help
>posts a 3 comment essay on why proton sdk sucks

**Comment by Bexpg-0** [comment]
> > help
> 
> >posts a 3 comment essay on why proton sdk sucks

https://youtu.be/nP40CUnBohY
